### ISSUE TITLE
Duplicate Somfy Library

### ISSUE THREAD

**Issue by Legion2** [aszopko/somfy-esp8266#1]
Hi, I also created a Somfy library based on the work of Nickduino, called [Somfy Remote Lib](https://github.com/Legion2/Somfy_Remote_Lib). It works with avr, esp8266 and esp32 and provides a simple API to send commands. It does not provide direct MQTT integration, but is flexible and was already integrated in [OpenMQTTGateway](https://github.com/1technophile/OpenMQTTGateway). It also supports the CC1101 Transmitter Module to send with 433.42 Mhz.

You may want to use it as backend, so you don't have to maintain the low-level Somfy IO handling and can focus on the MQTT integration. Somfy Remote Lib is also available via the Arduino Library manager.

**Comment by aszopko** [comment]
Hi there, thanks for the info. I will check that out if I need to edit the lib.
