### ISSUE TITLE
EEPROM endurance

### ISSUE THREAD

**Issue by KLelong** [aszopko/somfy-esp8266#2]
Hi,
First I should say that I have no experience with somfy. But there is a possibility that I will use somfy devices in the near future.

Now the rolling code is stored in EEPROM. Have you any idea about the endurance of the EEPROM ? I'm using EEPROM in projects, but there that's only for configuration options that rarely change.
I would like to propose an alternative method of storing that rolling code, but that depends on MQTT.
The device should subscribe to a "retained" MQTT topic. Every time the rolling code is updated, it publishes that code to that retained topic.
So at boot, it gets the latest rolling code and continues.
It would even be possible to have other devices use that same rolling code. E.g. when replacing broken hardware, that device would not need to register with the somfy device.

Just a thought.

**Comment by aszopko** [comment]
Hello,

All I can say about the endurance of the  EEPROM storage is that the Nodemcu I use with the Somfy lib has plenty more different tasks, therefore updates (OTA), and restarts are not uncommon. I don't remember that I needed to reprogram it, it does its job for quite a few months now.
Although with your idea this feature would be more robust, I might implement it in the future. Thanks!
